services:
  mysql:
    image: mysql:latest
    container_name: patient-reports-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example_root_pwd
      MYSQL_DATABASE: mydb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"  # Using 3307 on host to avoid conflicts
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "appuser", "-papppass"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-reports-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://appuser:apppass@mysql:3306/mydb
      - NODE_ENV=development
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: