services:
  mysql:
    image: mysql:latest
    container_name: mysql-vector-demo
    environment:
      MYSQL_ROOT_PASSWORD: example_root_pwd
      MYSQL_DATABASE: mydb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      
volumes:
  mysql_data: